//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetToJScript.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetToJScript.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function setversion() {
        ///  var shell = new ActiveXObject(&apos;WScript.Shell&apos;);
        ///  ver = &apos;v4.0.30319&apos;;
        ///  try {
        ///    shell.RegRead(&apos;HKLM\\SOFTWARE\\Microsoft\\.NETFramework\\v4.0.30319\\&apos;);
        ///  } catch(e) { 
        ///    ver = &apos;v2.0.50727&apos;;
        ///  }
        ///  shell.Environment(&apos;Process&apos;)(&apos;COMPLUS_Version&apos;) = ver;
        ///}
        ///.
        /// </summary>
        internal static string jscript_auto_version_script {
            get {
                return ResourceManager.GetString("jscript_auto_version_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var serialized_obj = [
        ///%SERIALIZED%
        ///];
        ///var entry_class = &apos;%CLASS%&apos;;
        ///
        ///try {
        ///    setversion();
        ///    var stm = new ActiveXObject(&apos;System.IO.MemoryStream&apos;);
        ///    var fmt = new ActiveXObject(&apos;System.Runtime.Serialization.Formatters.Binary.BinaryFormatter&apos;);
        ///    var al = new ActiveXObject(&apos;System.Collections.ArrayList&apos;)
        ///
        ///    for (i in serialized_obj) {
        ///        stm.WriteByte(serialized_obj[i]);
        ///    }
        ///
        ///    stm.Position = 0;
        ///    var n = fmt.SurrogateSelector;
        ///    var d = fmt.Deserialize_2(stm);
        ///    a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jscript_template {
            get {
                return ResourceManager.GetString("jscript_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos;?&gt;
        ///&lt;package&gt;
        ///&lt;component id=&apos;dummy&apos;&gt;
        ///&lt;registration
        ///  description=&apos;dummy&apos;
        ///  progid=&apos;dummy&apos;
        ///  version=&apos;1.00&apos;
        ///  remotable=&apos;True&apos;&gt;
        ///&lt;/registration&gt;
        ///&lt;/component&gt;
        ///&lt;/package&gt;.
        /// </summary>
        internal static string scriptlet_template {
            get {
                return ResourceManager.GetString("scriptlet_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Function decodeHex(hex)
        ///    On Error Resume Next
        ///    Dim DM, EL
        ///    Set DM = CreateObject(&quot;Microsoft.XMLDOM&quot;)
        ///    Set EL = DM.createElement(&quot;tmp&quot;)
        ///    EL.DataType = &quot;bin.hex&quot;
        ///    EL.Text = hex
        ///    decodeHex = EL.NodeTypedValue
        ///End Function
        ///
        ///Function Run()
        ///    Dim serialized_obj
        ///    %SERIALIZED%
        ///
        ///    entry_class = &quot;%CLASS%&quot;
        ///
        ///    Dim stm As Object, fmt As Object, al As Object
        ///    Set stm = CreateObject(&quot;System.IO.MemoryStream&quot;)
        ///    Set fmt = CreateObject(&quot;System.Runtime.Serialization [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vba_template {
            get {
                return ResourceManager.GetString("vba_template", resourceCulture);
            }
        }
    }
}
